services:
  - type: web
    name: smart-career-advisor
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000  # or leave empty if Render will auto-assign
